Weather/WeatherApp/config/routes.rb
Rails.application.routes.draw do
  resources :precipitation_measurements

end

Weather/WeatherApp/app/models/precipitation_measurement.rb
class PrecipitationMeasurement
  include Mongoid::Document
  field :STATION, type: String
  field :ELEVATION, type: Integer
  field :LATITUDE, type: Float
  field :LONGITUDE, type: Float
  field :DATE, type: String
  field :YTD_PRECIP_NORM, type: Integer
  field :YTD2013_PRECIP, type: Integer
  field :PRECIP2013_DIFF, type: Integer
  field :YTD2014_PRECIP, type:  Integer
  field :PRECIP2014_DIFF, type: Integer
  field :YTD2015_PRECIP, type: Integer
  field :PRECIP2015_DIFF, type: Integer
end

Weather/WeatherApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Weather/WeatherApp/app/controllers/precipitation_measurements_controller.rb
class PrecipitationMeasurementsController < ApplicationController
  before_action :set_precipitation_measurement, only: [:show, :edit, :update, :destroy]

  # GET /precipitation_measurements
  # GET /precipitation_measurements.json
  def index
    @precipitation_measurements = PrecipitationMeasurement.all
  end

  # GET /precipitation_measurements/1
  # GET /precipitation_measurements/1.json
  def show
  end

  # GET /precipitation_measurements/new
  def new
    @precipitation_measurement = PrecipitationMeasurement.new
  end

  # GET /precipitation_measurements/1/edit
  def edit
  end

  # POST /precipitation_measurements
  # POST /precipitation_measurements.json
  def create
    @precipitation_measurement = PrecipitationMeasurement.new(precipitation_measurement_params)

    respond_to do |format|
      if @precipitation_measurement.save
        format.html { redirect_to @precipitation_measurement, notice: 'Precipitation measurement was successfully created.' }
        format.json { render :show, status: :created, location: @precipitation_measurement }
      else
        format.html { render :new }
        format.json { render json: @precipitation_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /precipitation_measurements/1
  # PATCH/PUT /precipitation_measurements/1.json
  def update
    respond_to do |format|
      if @precipitation_measurement.update(precipitation_measurement_params)
        format.html { redirect_to @precipitation_measurement, notice: 'Precipitation measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @precipitation_measurement }
      else
        format.html { render :edit }
        format.json { render json: @precipitation_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /precipitation_measurements/1
  # DELETE /precipitation_measurements/1.json
  def destroy
    @precipitation_measurement.destroy
    respond_to do |format|
      format.html { redirect_to precipitation_measurements_url, notice: 'Precipitation measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_precipitation_measurement
      @precipitation_measurement = PrecipitationMeasurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def precipitation_measurement_params
      params.require(:precipitation_measurement).permit(:STATION, :ELEVATION, :LATITUDE, :LONGITUDE, :DATE, :YTD_PRECIP_NORM, :YTD2013_PRECIP, :PRECIP2013_DIFF, :YTD2014_PRECIP, :PRECIP2014_DIFF, :YTD2015_PRECIP, :PRECIP2015_DIFF)
    end
end

Weather/WeatherApp/app/helpers/application_helper.rb
module ApplicationHelper
end

Weather/WeatherApp/app/helpers/precipitation_measurements_helper.rb
module PrecipitationMeasurementsHelper
end

Weather/WeatherApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Weather/WeatherApp/app/views/precipitation_measurements/_form.html.erb
<%= form_for(@precipitation_measurement) do |f| %>
  <% if @precipitation_measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@precipitation_measurement.errors.count, "error") %> prohibited this precipitation_measurement from being saved:</h2>

      <ul>
      <% @precipitation_measurement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :STATION %><br>
    <%= f.text_field :STATION %>
  </div>
  <div class="field">
    <%= f.label :ELEVATION %><br>
    <%= f.number_field :ELEVATION %>
  </div>
  <div class="field">
    <%= f.label :LATITUDE %><br>
    <%= f.text_field :LATITUDE %>
  </div>
  <div class="field">
    <%= f.label :LONGITUDE %><br>
    <%= f.text_field :LONGITUDE %>
  </div>
  <div class="field">
    <%= f.label :DATE %><br>
    <%= f.text_field :DATE %>
  </div>
  <div class="field">
    <%= f.label :YTD_PRECIP_NORM %><br>
    <%= f.text_field :YTD_PRECIP_NORM %>
  </div>
  <div class="field">
    <%= f.label :YTD2013_PRECIP %><br>
    <%= f.text_field :YTD2013_PRECIP %>
  </div>
  <div class="field">
    <%= f.label :PRECIP2013_DIFF %><br>
    <%= f.text_field :PRECIP2013_DIFF %>
  </div>
  <div class="field">
    <%= f.label :YTD2014_PRECIP %><br>
    <%= f.text_field :YTD2014_PRECIP %>
  </div>
  <div class="field">
    <%= f.label :PRECIP2014_DIFF %><br>
    <%= f.text_field :PRECIP2014_DIFF %>
  </div>
  <div class="field">
    <%= f.label :YTD2015_PRECIP %><br>
    <%= f.text_field :YTD2015_PRECIP %>
  </div>
  <div class="field">
    <%= f.label :PRECIP2015_DIFF %><br>
    <%= f.text_field :PRECIP2015_DIFF %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Weather/WeatherApp/app/views/precipitation_measurements/edit.html.erb
<h1>Editing Precipitation Measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @precipitation_measurement %> |
<%= link_to 'Back', precipitation_measurements_path %>

Weather/WeatherApp/app/views/precipitation_measurements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Precipitation Measurements</h1>

<table>
  <thead>
    <tr>
      <th>Station</th>
      <th>Elevation</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Date</th>
      <th>Ytd precip norm</th>
      <th>Ytd2013 precip</th>
      <th>Precip2013 diff</th>
      <th>Ytd2014 precip</th>
      <th>Precip2014 diff</th>
      <th>Ytd2015 precip</th>
      <th>Precip2015 diff</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @precipitation_measurements.each do |precipitation_measurement| %>
      <tr>
        <td><%= precipitation_measurement.STATION %></td>
        <td><%= precipitation_measurement.ELEVATION %></td>
        <td><%= precipitation_measurement.LATITUDE %></td>
        <td><%= precipitation_measurement.LONGITUDE %></td>
        <td><%= precipitation_measurement.DATE %></td>
        <td><%= precipitation_measurement.YTD_PRECIP_NORM %></td>
        <td><%= precipitation_measurement.YTD2013_PRECIP %></td>
        <td><%= precipitation_measurement.PRECIP2013_DIFF %></td>
        <td><%= precipitation_measurement.YTD2014_PRECIP %></td>
        <td><%= precipitation_measurement.PRECIP2014_DIFF %></td>
        <td><%= precipitation_measurement.YTD2015_PRECIP %></td>
        <td><%= precipitation_measurement.PRECIP2015_DIFF %></td>
        <td><%= link_to 'Show', precipitation_measurement %></td>
        <td><%= link_to 'Edit', edit_precipitation_measurement_path(precipitation_measurement) %></td>
        <td><%= link_to 'Destroy', precipitation_measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Precipitation measurement', new_precipitation_measurement_path %>

Weather/WeatherApp/app/views/precipitation_measurements/new.html.erb
<h1>New Precipitation Measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', precipitation_measurements_path %>

Weather/WeatherApp/app/views/precipitation_measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station:</strong>
  <%= @precipitation_measurement.STATION %>
</p>

<p>
  <strong>Elevation:</strong>
  <%= @precipitation_measurement.ELEVATION %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @precipitation_measurement.LATITUDE %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @precipitation_measurement.LONGITUDE %>
</p>

<p>
  <strong>Date:</strong>
  <%= @precipitation_measurement.DATE %>
</p>

<p>
  <strong>Ytd precip norm:</strong>
  <%= @precipitation_measurement.YTD_PRECIP_NORM %>
</p>

<p>
  <strong>Ytd2013 precip:</strong>
  <%= @precipitation_measurement.YTD2013_PRECIP %>
</p>

<p>
  <strong>Precip2013 diff:</strong>
  <%= @precipitation_measurement.PRECIP2013_DIFF %>
</p>

<p>
  <strong>Ytd2014 precip:</strong>
  <%= @precipitation_measurement.YTD2014_PRECIP %>
</p>

<p>
  <strong>Precip2014 diff:</strong>
  <%= @precipitation_measurement.PRECIP2014_DIFF %>
</p>

<p>
  <strong>Ytd2015 precip:</strong>
  <%= @precipitation_measurement.YTD2015_PRECIP %>
</p>

<p>
  <strong>Precip2015 diff:</strong>
  <%= @precipitation_measurement.PRECIP2015_DIFF %>
</p>

<%= link_to 'Edit', edit_precipitation_measurement_path(@precipitation_measurement) %> |
<%= link_to 'Back', precipitation_measurements_path %>